on: 
  push:
    branches:
      - main

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout branch
        uses: actions/checkout@v3
      
      - name: install node 
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      
      - name: init pnpm
        uses: pnpm/action-setup@v2
      
      - name: install packages
        run: pnpm install
      
      - name: build static
        run: npm run build

      - name: deploy to vps
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "./dist"
          EXCLUDE: "/.github/, /.git/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html"